version: "2.4"

services:

  center:
    image: public.ecr.aws/variocube/center:latest
    container_name: center
    ports:
      - "7000:7000"

  center-admin:
    image: public.ecr.aws/variocube/center-admin:latest
    container_name: center-admin
    ports:
      - "7001:7001"

  controller:
    image: public.ecr.aws/variocube/controller:latest
    container_name: controller
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: /application.yml
    volumes:
      - ./controller.yml:/application.yml:ro
    ports:
      - "9000:9000"

  app-host:
    image: public.ecr.aws/variocube/app-host:latest
    container_name: app-host
    ports:
      - "4000:4000"

